# Generated by Django 3.0.7 on 2020-06-25 18:58

import cuser.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditTrail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('delstatus', models.BooleanField(default=False)),
                ('deldate', models.DateTimeField(blank=True, null=True)),
                ('obj_model', models.CharField(blank=True, max_length=500, null=True, verbose_name='Object Model')),
                ('server', models.CharField(blank=True, max_length=50, null=True, verbose_name='Server')),
                ('remote_address', models.CharField(blank=True, max_length=50, null=True)),
                ('ref_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='Ref Type')),
                ('ref_value', models.IntegerField(blank=True, null=True, verbose_name='Ref Value(INT)')),
                ('message', models.TextField(blank=True, null=True, verbose_name='Message')),
                ('is_alert', models.BooleanField(default=False)),
                ('creator', cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='m_audit_trail', to=settings.AUTH_USER_MODEL, verbose_name='createby')),
            ],
            options={
                'verbose_name': 'Audit Trail',
                'verbose_name_plural': 'Audit Trails',
                'db_table': 'm_audit_trail',
            },
        ),
    ]
