# Generated by Django 3.0.7 on 2020-06-25 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebScrapper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('delstatus', models.BooleanField(default=False)),
                ('deldate', models.DateTimeField(blank=True, null=True)),
                ('domain_name', models.CharField(max_length=225)),
                ('location', models.CharField(blank=True, max_length=500, null=True)),
                ('urls_page', models.CharField(blank=True, max_length=500, null=True)),
                ('max_page', models.IntegerField(blank=True, null=True)),
                ('done', models.IntegerField(blank=True, default=0, null=True)),
            ],
            options={
                'verbose_name_plural': 'Web Scrappers',
                'db_table': 'web_scrapper',
                'ordering': ['domain_name', 'location'],
            },
        ),
        migrations.CreateModel(
            name='WebScrapperDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('delstatus', models.BooleanField(default=False)),
                ('deldate', models.DateTimeField(blank=True, null=True)),
                ('urls_detail', models.CharField(blank=True, max_length=500, null=True)),
                ('done', models.IntegerField(blank=True, default=0, null=True)),
                ('web_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='scrappers.WebScrapper')),
            ],
            options={
                'verbose_name_plural': 'Web Scrapper Detail Pages',
                'db_table': 'web_scrapper_detail',
                'ordering': ['web_source__domain_name', 'urls_detail'],
            },
        ),
    ]
