#!/bin/sh
# NOTE: This file is only used for localhost development. A similar is generated
# by ansible when deploying to real environments.

export BASE_URL="http://localhost:8000"
export DJANGO_SECRET_KEY="^t46w^zsxt3mp4td0tc0m1dt5zov%4@eq@j8e%hrm3g_#3nbp%-e"

# export ELASTICSEARCH_BASE='http://35.247.184.220/elasticsearch' # live
export ELASTICSEARCH_BASE='http://35.240.130.239/elasticsearch' # staging

# gcp cloud sql - postgresql LIVE Server
# export POSTGRESQL_USER="postgres"
# export POSTGRESQL_PORT="5432"
# export POSTGRESQL_NAME="halalmas"
# export POSTGRESQL_HOST="34.87.91.46" 
# export POSTGRESQL_PASSWORD="!!tempat!!"


# gcp cloud sql - postgresql staging Server
export POSTGRESQL_USER="postgres"
export POSTGRESQL_PORT="5432"
export POSTGRESQL_NAME="halalmas-staging2"
export POSTGRESQL_HOST="34.87.91.46" 
export POSTGRESQL_PASSWORD="!!tempat!!"


# postgresql localhost
# export POSTGRESQL_USER="halalmas"
# export POSTGRESQL_PORT="5432"
# export POSTGRESQL_NAME="halalmas_db"
# export POSTGRESQL_HOST="localhost" 
# export POSTGRESQL_PASSWORD="!!halalmas!!"

# local mysql
# export MYSQL_USER="xworkuser"
# export MYSQL_PORT="3306"
# export MYSQL_HOST="localhost" 
# export MYSQL_PASSWORD="QX0HB6W9J6TBUAXTYGN1MZEAEJ4GL4P0TSKTSYECCO2HZS3FW7"
# export MYSQL_NAME='xwork_server'

# live mysql
# export MYSQL_USER="xworkLiveuserdb2"
# export MYSQL_PORT="3306"
# export MYSQL_HOST="35.240.191.149" 
# export MYSQL_PASSWORD="xworkDB3ZxVS3WnqF5nMysqlPWDR37pB2LpTyU2LR37pB2LpTyU2L"
# export MYSQL_NAME='xworkserver'

# staging mysql
export MYSQL_USER="xworkLiveuserdb2"
export MYSQL_PORT="3306"
export MYSQL_HOST="35.240.191.149" 
export MYSQL_PASSWORD="xworkDB3ZxVS3WnqF5nMysqlPWDR37pB2LpTyU2LR37pB2LpTyU2L"
export MYSQL_NAME='xworkserver_staging'

export SENTRY_DSN=""
export GOOGLE_MAPS_API_KEY="AIzaSyAGbvDXh9A8ysuD2fZAuuqe35ZsLb3x_Iw"

# AWS - S3
export S3_BUCKET_NAME="halalmas"
export S3_BUCKET_GALLERY="halalmas"
export COMPRESS_IMAGE_FORMAT="JPEG"

export AWS_PUBLIC_MEDIA_LOCATION="server/media_dev/public"
export AWS_PRIVATE_MEDIA_LOCATION="server/media_dev/private"

# AWS - IM
export AWS_ACCESS_KEY_ID="AKIAIJ5ZERDP33U5HSSQ"
export AWS_SECRET_ACCESS_KEY="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"
export AWS_S3_DEFAULT_REGION="ap-southeast-1"

# AWS - SES
export SES_ACCESS_KEY="AKIAJKAEUT5TBYUZ7GDA"
export SES_SECRET_KEY="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"
export SES_REGION="us-west-2"

# EMAIL
export EMAIL_TESTING="cobaan.xwork@gmail.com" #"cobaan.halalmas@gmail.com"
export EMAIL_TECH_TEAM="cobaan.xwork@gmail.com" #"tech@halalmas.com"

# CELERY
# export CELERY_BROKER_URL="amqp://halalmas_user:!!halalmasPWd21!!@localhost:5672//"
export CELERY_BROKER_URL="pyamqp://halalmas_user:!!halalmasPWd21!!@localhost:5672//"
export CELERY_RUNNING="TRUE"

#facebook evee.tempat.com
export FACEBOOK_SECRET_KEY="91dd85dcd8276c354bbac28f4da7b863"
export FACEBOOK_APP_ID="369966020292641"

export halalmas_URL="http://abra.tempat.com"
export halalmas_PROJ="SERVER"