# Generated by Django 3.0.7 on 2020-06-25 18:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServerConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('delstatus', models.BooleanField(default=False)),
                ('deldate', models.DateTimeField(blank=True, null=True)),
                ('config_name', models.CharField(max_length=100, verbose_name='Configuration Name')),
                ('config_value_int', models.FloatField(blank=True, null=True, verbose_name='Value in Number')),
                ('config_value_str', models.CharField(blank=True, max_length=250, null=True, verbose_name='Value in String')),
                ('config_status', models.BooleanField(default=False, verbose_name='Value in Boolean')),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('is_active', models.BooleanField(blank=True, default=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Server Configuration',
                'db_table': 'm_server_configuration',
                'ordering': ['config_name'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalServerConfiguration',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('cdate', models.DateTimeField(blank=True, editable=False)),
                ('udate', models.DateTimeField(blank=True, editable=False)),
                ('delstatus', models.BooleanField(default=False)),
                ('deldate', models.DateTimeField(blank=True, null=True)),
                ('config_name', models.CharField(max_length=100, verbose_name='Configuration Name')),
                ('config_value_int', models.FloatField(blank=True, null=True, verbose_name='Value in Number')),
                ('config_value_str', models.CharField(blank=True, max_length=250, null=True, verbose_name='Value in String')),
                ('config_status', models.BooleanField(default=False, verbose_name='Value in Boolean')),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('is_active', models.BooleanField(blank=True, default=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical server configuration',
                'db_table': 'm_server_configuration_history',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='CalendarDimension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('delstatus', models.BooleanField(default=False)),
                ('deldate', models.DateTimeField(blank=True, null=True)),
                ('year', models.IntegerField(verbose_name='Year')),
                ('month', models.IntegerField(verbose_name='Month')),
            ],
            options={
                'verbose_name_plural': 'Calendar Dimensions',
                'db_table': 'm_calendar_dimension',
                'ordering': ['year', 'month'],
                'unique_together': {('year', 'month')},
            },
        ),
        migrations.CreateModel(
            name='CalendarDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('delstatus', models.BooleanField(default=False)),
                ('deldate', models.DateTimeField(blank=True, null=True)),
                ('calendar_date', models.DateField(verbose_name='Calendar Date')),
                ('status', models.CharField(blank=True, choices=[('DAY_OFF', 'DAY OFF'), ('WEEKEND', 'HOLIDAY'), ('SPECIAL', 'SPECIAL'), ('GOOGLE', 'WEEKEND'), ('WEEKDAY', 'WEEKDAY')], default='WEEKDAY', help_text='set categories for this date.', max_length=50, null=True, verbose_name='Status Date')),
                ('dimension', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='configuration.CalendarDimension')),
            ],
            options={
                'verbose_name_plural': 'Calendar Dates',
                'db_table': 'm_calendar_date',
                'ordering': ['dimension__year', 'dimension__month', 'calendar_date'],
            },
        ),
    ]
